// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCHkxgjwbmbXUdDwo3OD1PNj4BA5qEnVE',
    appId: '1:508780810247:web:b574e32ac48f1b7afe9aa2',
    messagingSenderId: '508780810247',
    projectId: 'pulse-social-4ee66',
    authDomain: 'pulse-social-4ee66.firebaseapp.com',
    storageBucket: 'pulse-social-4ee66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL6fpmSOGzfioMTD9ITUyEpuZ_XKywHsM',
    appId: '1:508780810247:android:b2d971303b0740d5fe9aa2',
    messagingSenderId: '508780810247',
    projectId: 'pulse-social-4ee66',
    storageBucket: 'pulse-social-4ee66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO5oDGa2fnbhqr923PrREfKf_-Z00J90s',
    appId: '1:508780810247:ios:944060a9730435c0fe9aa2',
    messagingSenderId: '508780810247',
    projectId: 'pulse-social-4ee66',
    storageBucket: 'pulse-social-4ee66.appspot.com',
    iosBundleId: 'com.example.pulseSocial',
  );
}
